name: pi_flutter_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
<<<<<<< HEAD
  shared_preferences: ^2.0.13
  jwt_decoder: ^2.0.1
=======
  shared_preferences: 
  jwt_decoder:
>>>>>>> a01410bb6bfd1eb646cc8dd59edd5ed103c2a060
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
